AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to provision EKS for running Helmfile.

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: my-eks-cluster
      Version: "1.27"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSSecurityGroup
        SubnetIds:
          - subnet-xxxxxxxx
          - subnet-yyyyyyyy

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EKSClusterRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: !GetAtt NodeRole.Arn
      ScalingConfig:
        MinSize: 1
        MaxSize: 3
        DesiredSize: 2
#      Subnets:
#        - subnet-xxxxxxxx
#        - subnet-yyyyyyyy

  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EKSNodeRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  HelmfileNamespace:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: helmfile
      ResolveConflicts: OVERWRITE

Outputs:
  EKSClusterName:
    Description: Name of the EKS Cluster
    Value: !Ref EKSCluster


#  aws cloudformation deploy --stack-name eks-stack --template-file eks-template.yaml --capabilities CAPABILITY_NAMED_IAM
#Run Helmfile on EKS:

#  Install kubectl and helmfile
#  Use kubectl to connect to EKS
#  Deploy your Helmfile charts