AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Fargate Cluster Setup with VPC, Subnets, Bastion Server, and Security Groups

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: NewEc2Pair
    Description: Name of an existing EC2 Key Pair

  BastionAllowedIP:
    Type: String
    Default: "0.0.0.0/0"
    Description: CIDR block allowed to access the Bastion host (e.g., '203.0.113.0/24')

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EKS-VPC
        - Key: aws:cloudformation:stack-name
          Value: !Ref AWS::StackName

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.0.0/24'
      AvailabilityZone: 'us-west-2a'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Private Subnet (for EKS Fargate)
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: 'us-west-2a'
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: EKS-Internet-Gateway

  # Attach the Internet Gateway to the VPC
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Bastion Security Group
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Bastion Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref BastionAllowedIP
      Tags:
        - Key: Name
          Value: Bastion-SG

  # EC2 Bastion Host
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      KeyName: !Ref KeyPairName
      ImageId: ami-0abcdef1234567890  # Replace with latest Amazon Linux 2 AMI
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: Bastion-Server
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y aws-cli

  # EKS Cluster IAM Role
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: 'Allow'
            Principal:
              Service: 'eks.amazonaws.com'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: eks-cluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PublicSubnet
          - !Ref PrivateSubnet
        SecurityGroupIds:
          - !Ref BastionSecurityGroup
        EndpointPublicAccess: false  # Security best practice
        EndpointPrivateAccess: true
      Tags:
        - Key: Name
          Value: EKS-Cluster

  # Fargate Pod Execution Role
  FargatePodExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: 'Allow'
            Principal:
              Service: 'eks-fargate.amazonaws.com'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy

  # EKS Fargate Profile
  FargateProfile:
    Type: AWS::EKS::FargateProfile
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: eks-fargate-profile
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets:
        - !Ref PrivateSubnet
      Selectors:
        - Namespace: default

Outputs:
  BastionPublicIP:
    Description: Public IP of the Bastion Host
    Value: !GetAtt BastionHost.PublicIp

  EKSClusterName:
    Description: EKS Cluster Name
    Value: !Ref EKSCluster

  FargateProfileName:
    Description: Fargate Profile Name
    Value: !Ref FargateProfile

  VPCId:
    Description: VPC ID
    Value: !Ref VPC

