apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-gm-config-server
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/gm-config-server/*.log
      pos_file /fluentd/log/gm-config-server.pos
      tag gm-config-server.log
      <parse>
        @type none
      </parse>
    </source>

    <match gm-config-server.log>
      @type stdout  # Replace this with your preferred output plugin
      @log_level info
    </match>

#Create this config on node using
#  kubectl apply -f fluentd-gm-config-server.yaml
