apiVersion: v1
kind: Service
metadata:
  name: gm-config-service
spec:
  type: NodePort
  selector:
    app: gm-config-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32697


