apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-aggregator-config
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>

    <match gm-access.log>
      @type kafka
      brokers kafka:9092  # Kafka service name and port
      topic_name gm-access-logs
      format json
    </match>
