apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-aggregator
  labels:
    app: fluentd-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-aggregator
  template:
    metadata:
      labels:
        app: fluentd-aggregator
    spec:
      containers:
        - name: fluentd
          image: fluentd
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
          command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-aggregator-config


#  Fluentd Aggregator Deployment
#  The aggregator node collects logs from sidecars and forwards them to Kafka.