services:
  gmUser:
    image: tobyawo/gm-user-service
    containerPort: 8087
    fluentd:
      enabled: true
      image: fluentd
      containerPort: 24225
    volumes:
      logPath: /var/log/gm-user
      fluentdConfigMap: fluentd-gm-user-config
    environment:
      springDatasourceUrl: jdbc:postgresql://postgresqlinstance.c2pcgeg0gpc2.us-east-1.rds.amazonaws.com:5432/postgres
      springDatasourceUsername: postgres
      springDatasourcePassword: postgres
      jwtSecret: somerandomsecret

      springJpaHibernateDdlAuto: update
      springJpaShowSql: true
      springJpaPropertiesHibernateFormatSql: true
      springJpaPropertiesHibernateDialect: org.hibernate.dialect.PostgreSQL95Dialect
