version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=BMv4Eo5_F5LivM9zTprv  # replace with your actual password
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true  # Enable enrollment token creation
    networks:
      - gm-services-docker-network
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    stdin_open: true
    tty: true

networks:
  gm-services-docker-network:
    external: true

volumes:
  es_data:
    driver: local
